pipeline {
    agent any
    tools {
        maven 'Maven 3.6.0'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }

        
        stage ('Build') {
        	steps {
				sh "mvn --version"
        		sh "mvn --batch-mode -V -U -e clean verify -Dsurefire.useFile=false -Dmaven.test.failure.ignore"

	        	junit testResults: '**/target/surefire-reports/TEST-*.xml'	        	
        	}
    	}

    	stage ('Analysis') {
    		steps {
        		sh "mvn -batch-mode -V -U -e checkstyle:checkstyle"
        		
        		recordIssues tools: [checkStyle()]
        	}
        }
    }
}